// Generated by gencpp from file serve_connection/Addints.msg
// DO NOT EDIT!


#ifndef SERVE_CONNECTION_MESSAGE_ADDINTS_H
#define SERVE_CONNECTION_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <serve_connection/AddintsRequest.h>
#include <serve_connection/AddintsResponse.h>


namespace serve_connection
{

struct Addints
{

typedef AddintsRequest Request;
typedef AddintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Addints
} // namespace serve_connection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serve_connection::Addints > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::serve_connection::Addints&) { return value(); }
};

template<>
struct DataType< ::serve_connection::Addints > {
  static const char* value()
  {
    return "serve_connection/Addints";
  }

  static const char* value(const ::serve_connection::Addints&) { return value(); }
};


// service_traits::MD5Sum< ::serve_connection::AddintsRequest> should match
// service_traits::MD5Sum< ::serve_connection::Addints >
template<>
struct MD5Sum< ::serve_connection::AddintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serve_connection::Addints >::value();
  }
  static const char* value(const ::serve_connection::AddintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serve_connection::AddintsRequest> should match
// service_traits::DataType< ::serve_connection::Addints >
template<>
struct DataType< ::serve_connection::AddintsRequest>
{
  static const char* value()
  {
    return DataType< ::serve_connection::Addints >::value();
  }
  static const char* value(const ::serve_connection::AddintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serve_connection::AddintsResponse> should match
// service_traits::MD5Sum< ::serve_connection::Addints >
template<>
struct MD5Sum< ::serve_connection::AddintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serve_connection::Addints >::value();
  }
  static const char* value(const ::serve_connection::AddintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serve_connection::AddintsResponse> should match
// service_traits::DataType< ::serve_connection::Addints >
template<>
struct DataType< ::serve_connection::AddintsResponse>
{
  static const char* value()
  {
    return DataType< ::serve_connection::Addints >::value();
  }
  static const char* value(const ::serve_connection::AddintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVE_CONNECTION_MESSAGE_ADDINTS_H
